// // code: 301, message: "이메일을 입력해주세요."
// // code: 302, message: "이메일은 30자리 미만으로 입력해주세요."
// code: 301, message: "이메일을 형식을 정확하게 입력해주세요."
// // code: 304, message: "비밀번호를 입력 해주세요."
// code: 302, message: "비밀번호는 6~20자리를 입력해주세요."
// code: 303, message: "닉네임을 입력 해주세요."
// // code: 307, message: "닉네임은 최대 20자리를 입력해주세요."
// code: 304, message: "중복된 이메일입니다."
// code: 305, message: "중복된 닉네임입니다."
