# GET

/check:
 get:
   security:
     - jwt: []
   tags:
     - Users
   description: Validate JWT token
   produces:
     - application/json
   responses:
      200:
        description: Authentication check success
        schema:
          $ref: "#/definitions/Validate_Success"

# POST

/user:
  post:
    description: Join to the application (Create User)
    tags:
     - Users
    produces:
      - application/json
    parameters:
      - name: email
        description: User's email to use for login.
        in: formData
        required: true
        type: string
      - name: nickname
        description: User's nickname.
        in: formData
        required: true
        type: string
      - name: name
        description: User's name.
        in: formData
        required: true
        type: string
      - name: password
        description: User's password.
        in: formData
        required: true
        type: string
    responses:
      200:
        description: Join success
        schema:
          $ref: "#/definitions/Join_Success"
/login:
  post:
    description: Log in to the application
    tags:
      - Users
    produces:
      - application/json
    parameters:
      - name: email
        description: User's email to use for login.
        in: formData
        required: true
        type: string
      - name: password
        description: User's password.
        in: formData
        required: true
        type: string
    responses:
      200:
        description: Log in success
        schema:
          $ref: "#/definitions/Login_Success"
